#!/usr/bin/env bash
# Callahan CI — One-line installer
# Usage: curl -fsSL https://getcallahan.dev | sh

set -e

CALLAHAN_VERSION="${CALLAHAN_VERSION:-latest}"
INSTALL_DIR="${CALLAHAN_INSTALL_DIR:-$HOME/.callahan}"
BINARY_DIR="${CALLAHAN_BIN_DIR:-/usr/local/bin}"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log() { echo -e "${BLUE}[callahan]${NC} $1"; }
ok()  { echo -e "${GREEN}[✓]${NC} $1"; }
err() { echo -e "${RED}[✗]${NC} $1" >&2; exit 1; }

echo ""
echo -e "${ORANGE}🔥 Callahan CI — AI-Native, Serverless CI/CD${NC}"
echo "─────────────────────────────────────────────"
echo ""

# Check prerequisites
log "Checking prerequisites..."

if ! command -v docker &>/dev/null; then
  err "Docker is required. Install it from https://docs.docker.com/get-docker/"
fi

DOCKER_COMPOSE_CMD=""
if docker compose version &>/dev/null 2>&1; then
  DOCKER_COMPOSE_CMD="docker compose"
elif command -v docker-compose &>/dev/null; then
  DOCKER_COMPOSE_CMD="docker-compose"
else
  err "Docker Compose is required."
fi

ok "Docker $(docker --version | awk '{print $3}' | tr -d ',')"
ok "Docker Compose available"

# Create install directory
mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"

# Download docker-compose.yml
log "Downloading Callahan..."
curl -fsSL "https://raw.githubusercontent.com/callahan-ci/callahan/main/docker-compose.yml" -o docker-compose.yml
ok "Downloaded docker-compose.yml"

# Create .env if it doesn't exist
if [ ! -f .env ]; then
  cat > .env <<EOF
# Callahan CI Configuration
# Generated by installer on $(date)

# Set at least one LLM API key:
ANTHROPIC_API_KEY=
OPENAI_API_KEY=
GROQ_API_KEY=

# Or use Ollama for local (offline) AI:
# docker compose --profile with-ollama up -d
# OLLAMA_URL=http://ollama:11434
# LLM_PROVIDER=ollama

# Security
JWT_SECRET=$(openssl rand -hex 32 2>/dev/null || cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)

# Port (default: 8080)
PORT=8080
EOF
  ok "Created .env file"
  echo ""
  echo -e "  ${ORANGE}⚠️  Action required:${NC} Add your LLM API key to ${INSTALL_DIR}/.env"
  echo -e "  Example: ${BLUE}ANTHROPIC_API_KEY=sk-ant-...${NC}"
  echo ""
fi

# Pull and start
log "Starting Callahan (this may take a moment on first run)..."
$DOCKER_COMPOSE_CMD pull -q
$DOCKER_COMPOSE_CMD up -d

# Wait for health
log "Waiting for Callahan to be ready..."
for i in {1..30}; do
  if curl -sf http://localhost:8080/health &>/dev/null; then
    break
  fi
  sleep 1
done

if curl -sf http://localhost:8080/health &>/dev/null; then
  ok "Callahan is running!"
else
  echo -e "${ORANGE}⚠️  Callahan may still be starting. Check logs with: cd ${INSTALL_DIR} && $DOCKER_COMPOSE_CMD logs${NC}"
fi

echo ""
echo -e "${GREEN}🚀 Callahan CI is ready!${NC}"
echo "─────────────────────────────────────────────"
echo -e "  Dashboard: ${BLUE}http://localhost:8080${NC}"
echo -e "  API:       ${BLUE}http://localhost:8080/api/v1${NC}"
echo -e "  Config:    ${BLUE}${INSTALL_DIR}/.env${NC}"
echo ""
echo "  Manage:"
echo -e "  ${ORANGE}cd ${INSTALL_DIR} && $DOCKER_COMPOSE_CMD logs -f${NC}   # View logs"
echo -e "  ${ORANGE}cd ${INSTALL_DIR} && $DOCKER_COMPOSE_CMD down${NC}       # Stop"
echo -e "  ${ORANGE}cd ${INSTALL_DIR} && $DOCKER_COMPOSE_CMD pull && $DOCKER_COMPOSE_CMD up -d${NC}  # Update"
echo ""
